### ISSUE TITLE
[BUG] Issue with conditional tags

### ISSUE THREAD

**Issue by blanklob** [Shopify/theme-check-vscode#144]
Hey there I have an issue with conditional tags the vscode extension reports an error but theme check deosn't thanks, here is a loom about the issue.

https://www.loom.com/share/1471e9b27acf4ab6896e354699c9ffe8

**Comment by charlespwd** [comment]
Yeah so this is caused because we don't have a way to parse IF tags as HTML tag names. 

Unfortunately, I don't have a fix for this because I believe it would make the syntax ambiguous. For the prettier plugin to work (and our LiquidHTML parser, which powers the [next version of theme check](https://github.com/shopify/theme-tools)), we kind of need to be slightly more specific about what we accept. 

You have a couple of options:

1. Dangling open/close nodes inside if statements are OK

```liquid
{% if cond %}
  <some-wrapper with-some-props>
{% else %}
  <some-other-wrapper with-some-other-props>
{% endif %}

{% if cond %}
  </some-wrapper>
{% else %}
  </some-other-wrapper>
{% endif %}
```

2. Name and props as variables

```liquid
{% liquid
  if cond
    assign wrapper = 'some-wrapper'
    assign props = '...'
  else
    assign wrapper = 'some-other-wrapper'
    assign props = '...'
  endif
%}
<{{ wrapper }} {{ props }}>

</{{ wrapper }}>
```

Known issues that don't work:
```liquid
<{% if cond %}wrapper props{% else %}other other-props{% endif %}>

</{% if cond %}wrapper{% else %}other{% endif %}>
```

Mostly because our LiquidHTML HTMLElement nodes are something like this type:
```ts
interface HTMLElement {
  name: (LiquidVariableOutput | TextNode)[]
  attributes: (HTMLAttribute | LiquidNode)[]
}
```

**Comment by blanklob** [comment]
Thanks!
