### ISSUE TITLE
New version 1.1.4 issues

### ISSUE THREAD

**Issue by lorand-horvath** [Shopify/theme-check-vscode#45]
In latest version 1.1.4 the changelog https://github.com/Shopify/theme-check-vscode/blob/main/CHANGELOG.md reads:
`1.1.4 / 2021-08-23
    Fix the where command for Windows (select the .bat file)
`
Shouldn't that be today's date, i.e. 2021-09-07 ?

Also, did you re-enable `shopify theme language-server` on Windows, as you have disabled it in the previous version 1.1.3, quoting from the changelog:
`1.1.3 / 2021-08-23
    Add Windows experimental warning in editor
    Disable shopify theme language-server on Windows until we fix the upstream bug (See (#42))
`

**Comment by lorand-horvath** [comment]
@charlespwd Is theme-check-vscode (VSCode Shopify Liquid extension) still disabled? Since #42 seems to be fixed, is there any other bug on Windows? The "weird in-between bug in Shopify CLI" - which one is it? Have you managed to fix it? I would appreciate an update on this because I would really like to use the VSCode extension at its full capability, without experimentation (if possible).

**Comment by charlespwd** [comment]
The reviews came _before_ I added the experimentation note :sweat_smile:. I believe that is why we got them. I believe the issue was partly a mix overconfidence and not enough windows users internally to file bug reports.

Since then, I _believe_ that all issues were fixed since we haven't had a new bug report in more than a week (and hundreds of new installs). Feels like we're getting there. But I'm more careful about removing the experimentation note. Expectations are very real and if you say something is ready for production, there is little room for error.

Haven't gotten around the Shopify CLI issue yet though. But you can install theme-check separately and it will work. There's nothing much different between the two, shopify-cli simply serves as a shell for the other so that you only need to install one thing instead of two.

Might be worth tackling before I leave on pat leave for 3 weeks.

**Comment by lorand-horvath** [comment]
> 
> 
> 
> Haven't gotten around the Shopify CLI issue yet though. But you can install theme-check separately and it will work. There's nothing much different between the two, shopify-cli simply serves as a shell for the other so that you only need to install one thing instead of two.
> 

The docs https://shopify.dev/themes/tools/theme-check/vscode say that Shopify CLI must be installed. I don't really understand, is the documentation outdated or misleading?

**Comment by charlespwd** [comment]
It's misleading. You _should_ be able to only install Shopify CLI (and that's what you need to do on mac/linux). But, for Windows only, that avenue doesn't work.

**Comment by lorand-horvath** [comment]
Well, that's not good news. I'll stick with Theme Kit, I guess? If this Shopify CLI / Theme Check doesn't work on Windows, is there an ETA for an actual working version?
I remember before Slate there was some other method, also locally installed Ruby-based solution (forgot its name), which didn't work either. So is Ruby so bad actually? Not supporting developers who work on Windows is honestly a bad move.
Shopify expects us to use the new tools Shopify CLI and Theme Check because of Online Store 2.0, but the tools are not working? What are we supposed to do? Buy a Mac or get used to using some wonky Linux distro?

**Comment by lorand-horvath** [comment]
Well, I guess Theme Kit it is then :(
