### ISSUE TITLE
Turn off automatic theme-check [Feature Request]

### ISSUE THREAD

**Issue by Kehza** [Shopify/theme-check-vscode#47]
So currently theme-check automatically runs upon opening a project, it would be nice to have the ability to disable this, and perhaps have an option to run it from .liquid files / commands. 

My reasons for this are: 
- Not all projects I open are Shopify related, I'm also far too lazy to enable/disable per workspace. 
- Some Shopify projects I work on are legacy, so theme-check isn't viable for them. 
- It can use a lot of resources, I may just want to do a small tweak in a project quickly.

**Comment by lokimckay** [comment]
Additional usage case/bug in favor of this feature:

Making a change to a theme file while also serving the theme via the Shopify CLI, causes this to happen:
1. Browser refreshes straight away
2. theme-check-vscode starts validating the theme
3. Browser finishes refreshing - with no visible changes changes because theme-check-vscode has not finished validation
4. theme-check-vscode finishes validation

A further manual refresh is required to actually see the changes in the browser

I'd like to disable the automatic validation entirely so that the changes go through immediately

**Comment by charlespwd** [comment]
Not that I remember. Workspace workflows is an area I haven't got time to consider yet.

Right now it works best when running with one project/root per VS Code window/workspace.

Supporting multiple roots or multiple theme-check.yml isn't supported as of now.

**Comment by lokimckay** [comment]
This was closed as completed but I couldn't find a related commit after a little hunting - am I right to assume we can achieve this using the `"themeCheck.checkOnSave": boolean` as per the README?
