### ISSUE TITLE
SpaceInsideBraces: Space missing before '%', but there is a space?

### ISSUE THREAD

**Issue by josefarrugia** [Shopify/theme-check-vscode#50]
Hello there,

I have noticed this strange bug saying that there is a space missing before `%` whilst there is a space though. I am currently using Visual Studio Code `1.60.1` and the Shopify Liquid extension `1.1.5`. Please see attached screenshots:

<img width="594" alt="space_missing_1" src="https://user-images.githubusercontent.com/8568008/133803226-dd6861f8-d389-4159-ad88-8dc833011751.png">
<img width="179" alt="space_missing_2" src="https://user-images.githubusercontent.com/8568008/133803239-49a762c3-6819-427d-b96c-79f89b5dadd6.png">

Have I missed something?

**Comment by charlespwd** [comment]
This has been fixed in theme-check 1.6.2.

To upgrade:

* If you have installed it via the Shopify CLI on brew, easiest way is to reinstall it to get the latest version of theme-check.

  ```
  brew uninstall shopify-cli
  brew install shopify-cli
  ```

* If you have installed it via Shopify CLI via the gem, reinstall it.

  ```
  gem uninstall shopify-cli
  gem install shopify-cli
  ```

* If you have installed theme-check via brew, upgrade it

  ```
  brew update && brew upgrade theme-check
  ```

* If you have installed it via the gem, upgrade it.

  ```
  gem update theme-check
  ```
