### ISSUE TITLE
The 'shopify' executable was not found on your $PATH

### ISSUE THREAD

**Issue by bigskillet** [Shopify/theme-check-vscode#51]
VS Code keeps giving me the following warning when the extension is enabled, but I'm not sure what to put in the extension settings to resolve the issue:

`The 'shopify' executable was not found on your $PATH. Was it installed? The path can also be changed via the "shopifyLiquid.shopifyCLIPath" setting.`

**Comment by charlespwd** [comment]
Hey @bigskillet, did you install the Shopify CLI or theme-check ([Instructions](https://shopify.dev/themes/tools/cli/installation#install-shopify-cli))?

If you did, what installation method did you use?

On what platform?

The message you're seeing happens when the VS Code extension cannot find an installed executable. If you did install it and the extension still says that it can't find it, then you'd need to do debug your system's $PATH environment variable.

**Comment by bigskillet** [comment]
Installed Shopify CLI via Homebrew, macOS.

How might I debug the $PATH environment variable?

**Comment by bigskillet** [comment]
VS Code wasn't opening from the terminal, with error `command not found: code`. Using the VS Code command palette, I ran `Shell Command: Install 'code' command in PATH` and it seems to have resolved the issue.

@charlespwd, I really appreciate your help walking me through this!

**Comment by charlespwd** [comment]
np!

**Comment by charlespwd** [comment]
Hmm. That must be it. In that case, I would suggest setting the path manually in your settings.json file.

`"shopifyLiquid.shopifyCLIPath": "/usr/local/bin/shopify",`

Should do the trick. Looks like the Quick Action doesn't load the environment variables.

**Comment by bigskillet** [comment]
Yep, that fixed it, thanks again!
