### ISSUE TITLE
Extension auto-corrects `nil` into `null`?

### ISSUE THREAD

**Issue by mohamedhaddi** [Shopify/theme-check-vscode#94]
I was customizing a liquid theme file, and as the extension started formatting the file on save, I noticed something weird:

[Screen Recording 2022-09-23 at 11.59.48.webm](https://user-images.githubusercontent.com/6943864/191947121-563deeb9-f941-4a58-a225-adbea3e8bc71.webm)

`nil` just turned into `null`. I never had something like this happen before. Can someone please try this on their end and let me know if they face a similar issue?

https://github.com/Shopify/theme-check-vscode/issues/94#tasklist-block-3b7d42b2-e3b5-41dd-b7e5-5422f9e7a1a0

**Comment by charlespwd** [comment]
That's intented behaviour that comes from https://github.com/shopify/prettier-plugin-liquid. 

In Liquid, those two are the same. For consistency, we decided to prefer `null` over `nil`. This was based off a quick poll in the partner slack sensing the general preference. 

We could make that configurable, but we'd need to get a bit of traction on that since we want to avoid having too many configurations to keep things simple (see [this principle](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/opinionated.md))

Feel free to open an issue in https://github.com/shopify/prettier-plugin-liquid to gather some support if that's something you'd be interested in.
